### PR TITLE
Minor Refinements 7

### LINKED ISSUE #49: Description and Popup Modal Issue
Carlos reported below issues for internal testing:
1. Description is too short, we need to store a longer text
2. Popup modal is closed easily when user clicks somewhere outside the popup, or press Escape button

### PR DESCRIPTION
**Pull request by dan-tang-ssd**
This PR is submitted to fix #49 

It contains below changes:
 - Change description column from string to text for tables communication_products, photos, evidence_attachments. It can store up to 65,535 chars instead of 255 chars now.
 - Upgrade filament package from version 3.2.40 to 3.2.114
 - Revise popup modal behaviour
   1. Disable closing the popup modal by clicking away
   2. Hide the popup modal "Close" button at upper right corner
   3. Disable closing the popup modal by pressing Escape key

The popup modal will only be closed by either clicking the "Create" or "Cancel" button now. Hopefully it can provide a better user experience.

---

Screen shot:

image

### CODE REVIEW

**Comment by dan-tang-ssd** [comment]
Hi @dave-mills , I need your help.

For this PR, I have upgraded filament package from version 3.2.40 to 3.2.114.
I run command "php artisan filament:upgrade" but it does not work.
So I have removed composer.lock and vendor folder, then run "composer install".
It installed filament 3.2.114 and I got a new composer.lock.

I pushed my new composer.lock to Github, and then submitted this PR.
There are two conflicts in composer.lock. I resolved them by keeping the delta change from this PR and removing the difference from dev branch.

When I deploy this PR to staging env, it has error about composer.lock (see below)

I remote to server, removed composer.lock and vendor folder, then run "composer install".
I also run command "php artisan migrate" and "php artisan up" to deploy this PR manually.
The application in staging env can run now.

The remaining problem is, when I click "Deploy Now" button in staging site, it produces the same error about composer.lock.
It looks like the forecoming PR will be affected... Would you advise how to resolve this?

---

Question:
 - Regarding staging and live deployment, do we have a standard way to manage the changes in composer.json and composer.lock?

---

Staging env deployment error:

```
Fri Sep 27 09:48:28 AM UTC 2024

Starting deployment...

Saved working directory and index state WIP on dev: fdb116b Merge pull request #50 from stats4sd/minor-refinements-7
From github.com:stats4sd/aef
 * branch            dev        -> FETCH_HEAD
Already up to date.

   INFO  Application is now in maintenance mode.  

   INFO  You may bypass maintenance mode via [http://staging-agroecology-cases.stats4sdtest.online/ihopeineverneedthis].  

Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. It is recommended that you run `composer update` or `composer update <package name>`.
- Required package "laravel/scout" is not present in the lock file.
This usually happens when composer files are incorrectly merged or the composer.json file is manually edited.
Read more about correctly resolving merge conflicts https://getcomposer.org/doc/articles/resolving-merge-conflicts.md
and prefer using the "require" command over editing the composer.json file directly https://getcomposer.org/doc/03-cli.md#require-r
```

**Comment by dave-mills** [comment]
@dan-tang-ssd - couple of things to help:

1. Remember that `composer update` is basically what you did manually with deleting the lock file and running `composer install`. Many composer-related issues can be solved by running `composer update` locally, and then committing the new lock file - so you definitely had the right approach! 

(As an aside, if you want to update a specific package but don't want to upgrade other things unnessecarily, you can do `composer update package/name`, e.g. `composer update filament/filament` will update Filament to the latest (3.2.114), along with any requirements for 3.2.114, without updating all the other packages.)

For this specific case, it looks like you got a fully working lock file with `composer update`, and _then_ you merged in the dev branch - which had some changes to the composer json file (Looking at that exact commit, I see that Ciara had added laravel/scout and livewire/livewire as requirements to the json file). I assume the merging of the lock files didn't work entirely, which is why the lock file on the current dev branch is not up-to-date. 

I think we can fix it with another composer update locally post-merge, and then committing the resulting lock file.

**Comment by dan-tang-ssd** [comment]
@dave-mills Thank you very much for your reply.

I have submitted and merged PR #51 to fix the composer issue.
It works gracefully with your suggestions. Thanks a lot.

**Comment by dave-mills** [comment]
[like]  Dave Mills reacted to your message:
________________________________

**Pull request merged**
